- hosts: 192.168.43.1
  tasks:
  - name: Configuring yum for Docker Repository
    yum_repository:
      name: Docker
      description: Docker Repoository
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
      gpgcheck: no
  - name: Installing  Docker in Managed node
    package: #installing docker
        name:  "docker-ce-18.09.1-3.el7.x86_64"
        state:  present
  - name: docker service
    service: #Docker service starting
          name:  "docker"
          state:  started
          enabled:  yes
  
  - name: pull an image
    docker_image:
       name: "vimal13/apache-webserver-php"
       source: pull
  - name: copying content in manged node
    copy:
          src: "index.html"
          dest:  "/pop/index.html"
  - name:  Creating  docker container
    docker_container:
           name:  "gajjuWebserver"
           image:  "vimal13/apache-webserver-php"
           state:  started
           exposed_ports:
           - "80"
           ports:
           -  "8080:80"
           volumes:
           -  /pop/:/var/www/html/
    
